name: Publish NuGet package

on:
  push:
    branches:
      - main
      

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Setup Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1

      - name: Install GitVersion.Tool
        uses: gittools/actions/gitversion/setup@v3.0.3
        with:
          versionSpec: '6.x'

      - name: Determine Version
        id: version
        uses: gittools/actions/gitversion/execute@v3.0.3
        with:
          useConfigFile: true
          configFilePath: './gitversion.yml'
          
      - name: Set NuGet version environment variable
        run: echo "NUGET_VERSION=${{ steps.version.outputs.MajorMinorPatch }}" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore Benchmark.Cli/Benchmark.Cli.csproj

      - name: Build project
        run: dotnet build --configuration Release Benchmark.Cli/Benchmark.Cli.csproj -p:Version=${{ env.NUGET_VERSION }}

      - name: Create NuGet package
        run: dotnet pack --configuration Release Benchmark.Cli/Benchmark.Cli.csproj -p:Version=${{ env.NUGET_VERSION }} --no-build --no-restore

      - name: Publish NuGet package
        run: dotnet nuget push Benchmark.Cli/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json